[[plugins]]
repo = 'keith/swift.vim'
on_ft = 'swift'

[[plugins]]
repo = 'apple/swift'
on_ft = 'sil'
rtp = 'utils/vim'

[[plugins]]
repo = 'EdJoJob/llvmir-vim'
on_ft = 'llvm'

[[plugins]]
repo = 'kateinoigakukun/swift-demangle-vim'
on_ft = ['sil', 'llvm']
hook_add = '''
    let g:swift_demangle#options = ['-compact']
    let g:swift_demangle#swift_path = expand('$HOME/.swiftenv/shims/swift')
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_source = '''
    let g:vim_markdown_folding_disabled = 1
    let g:vim_markdown_autowrite = 1
'''

[[plugins]]
repo = 'kateinoigakukun/previm'
on_ft = 'markdown'
hook_source = '''
    let g:previm_enable_realtime = 1
    let g:previm_show_header = 0
'''


[[plugins]]
repo = 'tyru/open-browser.vim'
on_source = ['previm']

[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1

[[plugins]]
repo = 'tpope/vim-surround'
on_i = 1

[[plugins]]
repo = 'godlygeek/tabular'
on_i = 1

[[plugins]]
repo = 'ujihisa/neco-ghc'
on_ft = 'haskell'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
